server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.1.110
  rabbitmq:
    virtual-host: /leyou
    username: leyou
    password: leyou
    host: 127.0.0.1
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
ly:
  jwt:
    pubKeyPath: /Users/bystander/id_rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称